### ISSUE TITLE
Multiple (Fixed part of code) Remotes & Stop

### ISSUE THREAD

**Issue by UziKhana** [rjcarlson49/homebridge-dooya-0#4]
Hey

Thanks for this little nugget, I got this to work with my venetian blinds! First ever dabble in Arduino and 433mhz space - good learning!

Not an issue, I have a few questions to better my understanding. 

1st Question on multiple remotes: I am assuming this is catering to having one remote (so one fixed part of the code) and multiple shades controlled by this one remote on different channels. In my case I have multiple remotes controlling 1 shade each. How do i adapt to that? Are multiple platforms allowed? 

2nd question on Stop. I don't see a stop code being sent at all. I thought the plugin would send a stop code after value in "Time it takes shade to open or close" (maxTime) but it seems to not do that. At first i thought my maxTime is possibly conflicting with xmitWait but tested and that is definitely not the case.

Lastly, a question that combines both of the above. On my venetian blinds to tilt-up or tilt-down (but remain closed) on the physical remote I would manually press UP then STOP after a few seconds and vice versa. To achieve this, given that there isn't a third button for STOP, I would imagine it would have to added as another shade but with a suitable (shorter) maxTime. Are such duplicates of the same shade allowed?

I have indeed tried to play with adding multiple platforms and shades but with no success.

One suggestion for what i think might be a typo; on the plugin settings form in the UI, where the 3 codes for Open, Close and Stop are defined the field label for Stop (third field) shows as "Code(s) for close (HEX) *", maybe you intended it to be "Code(s) for **_stop_** (HEX) *".

Many thanks
Uzi

**Comment by rjcarlson49** [comment]
Thanks, glad it helped.

Q1 - I don't think it matters that you have multiple remotes. A platform can contain multiple accessories, even different types of accessories. You just need to configure multiple shade accessories within your platform. Having a platform means that the parts of the config that apply equally to every shade need not be repeated.

Another method would be to implement an accessory only. However, that would require a config file for each one. Almost certainly that would be an unnecessary pain.

Q2 - Stop codes are sent only when the selected shade position is between 0 and 100. If 0 or 100 is selected, the shade is assumed to stop itself.

Q3 - If I understand this correctly, when your blinds are closed, for the first few seconds of 'Open' it is rotating the blinds. If you stop then, the blinds are tilted open, but not raised. From the way you described it. it sounds like your codes may work differently from mine. It may be that it moves while you press the button, then stops when you release it. That would imply that it moves while it is receiving codes, then stops when it stops receiving codes. My Arduino sketch would have to be modified to work in that manner. I guess it could also be that your remote sends "Up" at button down and 'Stop' at button up. That actually seems more likely to me than continuous transmit.

In any case, it appears that you need a timed 'Stop'. You need to determine how long from completely closed to tilted open. Then send your codes with that timing.

A different question is how you represent this in Homekit. HK has specific devices and characteristics that it understands. You need to find a device and set of characteristics among Apple's set that most closely matches your need. I believe there are characteristics that line up with a slatted venetian blind.

Thanks for th pointer to the typo.

-Good luck

**Comment by FA-Tech** [comment]
Hey,

i am struggling on the decoding part and hope you can help me. It is also my first time to connect the Arduino to the pi.

I understand the fixed part and the open part of the lower section but I don't know how to correctly interpret my decodings in terms of the timings ( what's the zero on, zero off etc part)

This is my Signal:

Detected OOK package	2022-02-03 17:51:32
Analyzing pulses...
Total count:  287,  width: 365.39 ms		(91348 S)
Pulse width distribution:
 [ 0] count:    7,  width: 4808 us [4796;4824]	(1202 S)
 [ 1] count:  162,  width:  376 us [356;396]	(  94 S)
 [ 2] count:  118,  width:  740 us [724;768]	( 185 S)
Gap width distribution:
 [ 0] count:    7,  width: 1480 us [1464;1500]	( 370 S)
 [ 1] count:  159,  width:  692 us [672;712]	( 173 S)
 [ 2] count:  117,  width:  328 us [300;368]	(  82 S)
 [ 3] count:    3,  width: 7912 us [7688;8028]	(1978 S)
Pulse period distribution:
 [ 0] count:    7,  width: 6288 us [6288;6296]	(1572 S)
 [ 1] count:  276,  width: 1068 us [1056;1108]	( 267 S)
 [ 2] count:    3,  width: 8404 us [8392;8436]	(2101 S)
Pulse timing distribution:
 [ 0] count:    7,  width: 4808 us [4796;4824]	(1202 S)
 [ 1] count:  279,  width:  356 us [300;396]	(  89 S)
 [ 2] count:  277,  width:  712 us [672;768]	( 178 S)
 [ 3] count:    7,  width: 1480 us [1464;1500]	( 370 S)
 [ 4] count:    3,  width: 7912 us [7688;8028]	(1978 S)
 [ 5] count:    1,  width: 48244 us [48244;48244]	(12061 S)
Level estimates [high, low]:  16129,   3108
RSSI: -0.1 dB SNR: 7.2 dB Noise: -7.2 dB
Frequency offsets [F1, F2]:   19533,      0	(+74.5 kHz, +0.0 kHz)
Guessing modulation: Pulse Width Modulation with sync/delimiter
view at https://triq.org/pdv/#AAB060060112C8016402C805C81EE8BC74839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1929292A1839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1929292A455+AAB089060112C8016402C805C81EE8BC74839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1929292A1839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1929292A1839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1A1A1A19455+AAB037060112C8016402C805C81EE8BC74839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1A1A1A19455+AAB037060112C8016402C805C81EE8BC74839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1A1A1A19555
Attempting demodulation... short_width: 376, long_width: 740, reset_limit: 8032, sync_width: 4808
Use a flex decoder with -X 'n=name,m=OOK_PWM,s=376,l=740,r=8032,g=0,t=0,y=4808'
pulse_demod_pwm(): Analyzer Device
bitbuffer:: Number of rows: 7 
[00] {40} d4 e0 f1 7e ee : 11010100 11100000 11110001 01111110 11101110 
[01] {40} d4 e0 f1 7e ee : 11010100 11100000 11110001 01111110 11101110 
[02] {40} d4 e0 f1 7e ee : 11010100 11100000 11110001 01111110 11101110 
[03] {40} d4 e0 f1 7e ee : 11010100 11100000 11110001 01111110 11101110 
[04] {40} d4 e0 f1 7e e1 : 11010100 11100000 11110001 01111110 11100001 
[05] {40} d4 e0 f1 7e e1 : 11010100 11100000 11110001 01111110 11100001 
[06] {40} d4 e0 f1 7e e1 : 11010100 11100000 11110001 01111110 11100001 

Thanks in advance

Felix
