### ISSUE TITLE
Decoding On off timing 

### ISSUE THREAD

**Issue by FA-Tech** [rjcarlson49/homebridge-dooya-0#8]
Hey,

i am struggling on the decoding part and hope you can help me. It is also my first time to connect the Arduino to the pi.

I understand the fixed part and the open part of the lower section but I don't know how to correctly interpret my decodings in terms of the timings ( what's the zero on, zero off etc part)

This is my Signal:

Detected OOK package 2022-02-03 17:51:32
Analyzing pulses...
Total count: 287, width: 365.39 ms (91348 S)
Pulse width distribution:
[ 0] count: 7, width: 4808 us [4796;4824] (1202 S)
[ 1] count: 162, width: 376 us [356;396] ( 94 S)
[ 2] count: 118, width: 740 us [724;768] ( 185 S)
Gap width distribution:
[ 0] count: 7, width: 1480 us [1464;1500] ( 370 S)
[ 1] count: 159, width: 692 us [672;712] ( 173 S)
[ 2] count: 117, width: 328 us [300;368] ( 82 S)
[ 3] count: 3, width: 7912 us [7688;8028] (1978 S)
Pulse period distribution:
[ 0] count: 7, width: 6288 us [6288;6296] (1572 S)
[ 1] count: 276, width: 1068 us [1056;1108] ( 267 S)
[ 2] count: 3, width: 8404 us [8392;8436] (2101 S)
Pulse timing distribution:
[ 0] count: 7, width: 4808 us [4796;4824] (1202 S)
[ 1] count: 279, width: 356 us [300;396] ( 89 S)
[ 2] count: 277, width: 712 us [672;768] ( 178 S)
[ 3] count: 7, width: 1480 us [1464;1500] ( 370 S)
[ 4] count: 3, width: 7912 us [7688;8028] (1978 S)
[ 5] count: 1, width: 48244 us [48244;48244] (12061 S)
Level estimates [high, low]: 16129, 3108
RSSI: -0.1 dB SNR: 7.2 dB Noise: -7.2 dB
Frequency offsets [F1, F2]: 19533, 0 (+74.5 kHz, +0.0 kHz)
Guessing modulation: Pulse Width Modulation with sync/delimiter
view at https://triq.org/pdv/#AAB060060112C8016402C805C81EE8BC74839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1929292A1839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1929292A455+AAB089060112C8016402C805C81EE8BC74839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1929292A1839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1929292A1839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1A1A1A19455+AAB037060112C8016402C805C81EE8BC74839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1A1A1A19455+AAB037060112C8016402C805C81EE8BC74839292A192A192A1A1929292A1A1A1A1A192929292A1A1A192A1929292929292A1929292A1A1A1A19555
Attempting demodulation... short_width: 376, long_width: 740, reset_limit: 8032, sync_width: 4808
Use a flex decoder with -X 'n=name,m=OOK_PWM,s=376,l=740,r=8032,g=0,t=0,y=4808'
pulse_demod_pwm(): Analyzer Device
bitbuffer:: Number of rows: 7
[00] {40} d4 e0 f1 7e ee : 11010100 11100000 11110001 01111110 11101110
[01] {40} d4 e0 f1 7e ee : 11010100 11100000 11110001 01111110 11101110
[02] {40} d4 e0 f1 7e ee : 11010100 11100000 11110001 01111110 11101110
[03] {40} d4 e0 f1 7e ee : 11010100 11100000 11110001 01111110 11101110
[04] {40} d4 e0 f1 7e e1 : 11010100 11100000 11110001 01111110 11100001
[05] {40} d4 e0 f1 7e e1 : 11010100 11100000 11110001 01111110 11100001
[06] {40} d4 e0 f1 7e e1 : 11010100 11100000 11110001 01111110 11100001

Thanks in advance

Felix

**Comment by rjcarlson49** [comment]
See the counts of 277 and 279 in pulse timing? These are the widths involved in making 1's and 0's. There are 7 pulses of 4808 and 1480. Since there are 7 rows, these apparently delineate the rows. Note that the pulses are 356 and 712. This is similar to the pulse period of 1068. So a 0 or 1 apparently consists of 356 on/off followed by 712 off/on.

That's what I remember anyway. I'll review my notes and comment further. I did this a while ago and I haven't looked at it since. My system has been perfectly stable however, somewhat to my surprise..
